services:
  - type: web
    name: lms-extractor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: TELEGRAM_BOT_TOKEN
        value: 8630040741:AAFIGza2z422T9x-m7H4k9Y8o1fkmkZKZXY
      - key: TELEGRAM_CHAT_ID
        value: 7363867528
